### ISSUE TITLE
Travis checks fail with AttributeError: 'module' object has no attribute 'test_imos'

### ISSUE THREAD

**Issue by mhidas** [aodn/cc-plugin-imos#11]
All Travis checks are failing with this error, even on master, which was passing before at exactly the same commit.
e.g. build [48](https://travis-ci.org/aodn/cc-plugin-imos/builds/379546999):
```
...
$ python setup.py test -s cc_plugin_imos.tests
running test
running egg_info
creating cc_plugin_imos.egg-info
writing requirements to cc_plugin_imos.egg-info/requires.txt
writing cc_plugin_imos.egg-info/PKG-INFO
writing top-level names to cc_plugin_imos.egg-info/top_level.txt
writing dependency_links to cc_plugin_imos.egg-info/dependency_links.txt
writing entry points to cc_plugin_imos.egg-info/entry_points.txt
writing manifest file 'cc_plugin_imos.egg-info/SOURCES.txt'
reading manifest file 'cc_plugin_imos.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'cc_plugin_imos.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    'cc_plugin_imos': ['tests/data/*.cdl']
  File "/home/travis/miniconda/envs/TEST/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/home/travis/miniconda/envs/TEST/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/travis/miniconda/envs/TEST/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/travis/miniconda/envs/TEST/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/travis/miniconda/envs/TEST/lib/python2.7/site-packages/setuptools/command/test.py", line 226, in run
    self.run_tests()
  File "/home/travis/miniconda/envs/TEST/lib/python2.7/site-packages/setuptools/command/test.py", line 248, in run_tests
    exit=False,
  File "/home/travis/miniconda/envs/TEST/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/home/travis/miniconda/envs/TEST/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/home/travis/miniconda/envs/TEST/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/home/travis/miniconda/envs/TEST/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/travis/miniconda/envs/TEST/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/home/travis/miniconda/envs/TEST/lib/python2.7/site-packages/setuptools/command/test.py", line 52, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/home/travis/miniconda/envs/TEST/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_imos'
The command "python setup.py test -s cc_plugin_imos.tests" exited with 1.
Done. Your build exited with 1.
```

**Comment by mhidas** [comment]
This is actually the same issue as #9. (Confusingly, the error message is different, but pinning the netCDF4 version to <1.4 fixes both.)
